### ISSUE TITLE
请问如何使用 PrepareCallback ?

### ISSUE THREAD

**Issue by DevDengChao** [aliyun/aliyun-tablestore-java-sdk#27]
目前该接口无任何入参, 而且在 Client 执行大部分操作时都会回调一次.
暂时无法理解这个回调接口的应用场景..

**Comment by zhouzf05** [comment]
有一些场景是使用临时账号来访问，临时账号会定期失效，所以在执行前需要检查账号是否失效，可以用 prepareCallback 来做。
