### ISSUE TITLE
GetRange方法不能正确的完成功能

### ISSUE THREAD

**Issue by gfl94** [aliyun/aliyun-tablestore-java-sdk#4]
[`OTSMultiDataSample.java`](https://github.com/aliyun/aliyun-tablestore-java-sdk/blob/master/src/test/java/examples/OTSMultiDataSample.java)中演示了`getRange`方法的调用，demo程序中，插入了GID=1， UID范围1-5的5条数据。

`getRange`设定了GID范围从1-4，但是返回的结果是所有1-5的条目，这里demo是有些问题的，返回1-5是正常的。

但是我把查询程序改成GID范围INF_MIN-INF_MAX，UID范围设置成1-4时仍然返回所有结果，这里是不是存在一些bug？

**Comment by qiyuewuyi** [comment]
第一个，你说的没问题，这个会修改掉。我们也欢迎你修改后给我们提pull request。
第二个，是没问题的，原因可以见这篇文章：[表格存储数据模型和查询操作](https://yq.aliyun.com/articles/38621)
